# **RECAP DATA PENJUALAN DAN PENDAPATAN BRAND NIKE**

# **IMPORT LIBRARY**

In [4]:
import pandas as pd

# **DATA FRAME**

In [5]:
file = "//content/drive/MyDrive/PRAK AVD/Nike_Sales_Uncleaned.csv"
df = pd.read_csv(file)

df

,Order_ID,Gender_Category,Product_Line,Product_Name,Size,Units_Sold,MRP,Discount_Applied,Revenue,Order_Date,Sales_Channel,Region,Profit
0,2000,Kids,Training,SuperRep Go,M,NaN,NaN,0.47,0.0,2024-03-09,Online,bengaluru,-770.45
1,2001,Women,Soccer,Tiempo Legend,M,3.0,4957.93,NaN,0.0,2024-07-09,Retail,Hyd,-112.53
2,2002,Women,Soccer,Premier III,M,4.0,NaN,NaN,0.0,NaN,Retail,Mumbai,3337.34
3,2003,Kids,Lifestyle,Blazer Mid,L,NaN,9673.57,NaN,0.0,04-10-2024,Online,Pune,3376.85
4,2004,Kids,Running,React Infinity,XL,NaN,NaN,NaN,0.0,2024/09/12,Retail,Delhi,187.89
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2495,4495,Kids,Basketball,Kyrie Flytrap,XL,3.0,NaN,NaN,0.0,2025-05-14,Online,Pune,2.97
2496,4496,Men,Basketball,Kyrie Flytrap,L,-1.0,NaN,NaN,0.0,NaN,Online,Hyd,-487.36
2497,4497,Men,Soccer,Tiempo Legend,7,NaN,6647.60,0.52,0.0,02-07-2025,Retail,Bangalore,-918.14
2498,4498,Women,Training,ZoomX Invincible,NaN,4.0,5358.70,NaN,0.0,11-12-2024,Online,Mumbai,3352.29
2499,4499,Women,Running,Air Zoom,M,NaN,5550.99,NaN,0.0,23-11-2024,Retail,Mumbai,2453.57

In [6]:
df.head(20)

,Order_ID,Gender_Category,Product_Line,Product_Name,Size,Units_Sold,MRP,Discount_Applied,Revenue,Order_Date,Sales_Channel,Region,Profit
0,2000,Kids,Training,SuperRep Go,M,NaN,NaN,0.47,0.00,2024-03-09,Online,bengaluru,-770.45
1,2001,Women,Soccer,Tiempo Legend,M,3.0,4957.93,NaN,0.00,2024-07-09,Retail,Hyd,-112.53
2,2002,Women,Soccer,Premier III,M,4.0,NaN,NaN,0.00,NaN,Retail,Mumbai,3337.34
3,2003,Kids,Lifestyle,Blazer Mid,L,NaN,9673.57,NaN,0.00,04-10-2024,Online,Pune,3376.85
4,2004,Kids,Running,React Infinity,XL,NaN,NaN,NaN,0.00,2024/09/12,Retail,Delhi,187.89
5,2005,Women,Training,Flex Trainer,M,1.0,7363.96,NaN,0.00,NaN,Retail,Delhi,1415.98
6,2006,Men,Training,SuperRep Go,M,NaN,6819.78,NaN,0.00,04-06-2025,Online,Bangalore,1802.09
7,2007,Kids,Training,SuperRep Go,M,1.0,NaN,0.32,0.00,NaN,Retail,Bangalore,2928.36
8,2008,Women,Soccer,Premier III,11,-1.0,NaN,NaN,0.00,11-10-2024,Online,Hyderabad,-731.18
9,2009,Men,Soccer,Mercurial Superfly,M,4.0,NaN,NaN,0.00,NaN,Online,Pune,3929.61
10,2010,Kids,Lifestyle,Waffle One,L,1.0,7949.83,NaN,0.00,2025/01/16,Online,Pune,1965.56
11,2011,Women,Training,Flex Trainer,L,-1.0,9586.08,NaN,0.00,NaN,Retail,Hyd,1667.08
12,2018,Kids,Lifestyle,Blazer Mid,NaN,-1.0,NaN,0.86,0.00,13-11-2024,Online,Delhi,2109.48
13,2013,Kids,Training,SuperRep Go,NaN,NaN,9671.05,NaN,0.00,19-09-2024,Online,hyderbad,299.34
14,2014,Women,Running,React Infinity,11,NaN,NaN,NaN,0.00,2025-04-12,Online,Bangalore,-1044.40
15,2015,Kids,Basketball,Air Jordan,NaN,NaN,3285.52,NaN,0.00,31-05-2025,Retail,Kolkata,1193.21
16,2016,Women,Basketball,Air Jordan,M,1.0,9871.75,0.30,6910.22,NaN,Retail,hyderbad,2452.69
17,2017,Women,Basketball,Air Jordan,9,4.0,NaN,NaN,0.00,17-03-2025,Retail,Delhi,1946.24
18,2018,Men,Training,Metcon 7,XL,0.0,NaN,1.17,0.00,NaN,Online,bengaluru,-966.89
19,2019,Kids,Running,Air Zoom,6,0.0,3424.06,0.32,0.00,2025/01/17,Online,Hyderabad,1915.24

In [8]:
df.tail(20)

,Order_ID,Gender_Category,Product_Line,Product_Name,Size,Units_Sold,MRP,Discount_Applied,Revenue,Order_Date,Sales_Channel,Region,Profit
2480,4480,Men,Training,SuperRep Go,7,NaN,NaN,0.61,0.00,05-05-2025,Retail,Hyderabad,1920.50
2481,4481,Men,Soccer,Mercurial Superfly,L,NaN,8504.98,0.88,0.00,11-12-2024,Retail,Delhi,1227.48
2482,4482,Kids,Soccer,Phantom GT,L,2.0,NaN,NaN,0.00,2024-07-16,Online,Mumbai,-742.03
2483,4483,Kids,Lifestyle,Blazer Mid,M,NaN,2844.04,0.12,0.00,12-06-2025,Online,Hyderabad,-1026.86
2484,4484,Men,Basketball,Air Jordan,11,3.0,5981.92,0.80,3589.15,2024/12/12,Retail,hyderbad,-751.05
2485,4485,Men,Training,Flex Trainer,L,NaN,NaN,0.78,0.00,2025/03/26,Retail,Pune,-367.25
2486,4486,Women,Training,Flex Trainer,XL,NaN,NaN,NaN,0.00,2023-10-15,Online,Bangalore,3338.79
2487,4487,Men,Lifestyle,Air Force 1,L,NaN,9009.71,0.40,0.00,21-08-2024,Retail,Pune,-996.86
2488,4488,Women,Training,Flex Trainer,8,2.0,NaN,NaN,0.00,2024/12/16,Retail,Pune,3045.38
2489,4489,Kids,Lifestyle,Blazer Mid,9,3.0,NaN,1.15,0.00,2025-04-02,Retail,bengaluru,1890.99
2490,4490,Women,Training,Metcon 7,L,0.0,NaN,NaN,0.00,23-02-2025,Online,Kolkata,-1173.84
2491,4491,Women,Running,Pegasus Turbo,M,0.0,NaN,NaN,0.00,NaN,Online,Kolkata,3066.85
2492,4492,Men,Lifestyle,Air Force 1,M,NaN,NaN,NaN,0.00,NaN,Retail,Mumbai,2397.23
2493,4493,Women,Lifestyle,Blazer Mid,XL,4.0,NaN,NaN,0.00,2024-10-04,Online,Mumbai,321.24
2494,4494,Women,Training,ZoomX Invincible,L,NaN,NaN,NaN,0.00,12-02-2025,Online,Kolkata,1357.29
2495,4495,Kids,Basketball,Kyrie Flytrap,XL,3.0,NaN,NaN,0.00,2025-05-14,Online,Pune,2.97
2496,4496,Men,Basketball,Kyrie Flytrap,L,-1.0,NaN,NaN,0.00,NaN,Online,Hyd,-487.36
2497,4497,Men,Soccer,Tiempo Legend,7,NaN,6647.60,0.52,0.00,02-07-2025,Retail,Bangalore,-918.14
2498,4498,Women,Training,ZoomX Invincible,NaN,4.0,5358.70,NaN,0.00,11-12-2024,Online,Mumbai,3352.29
2499,4499,Women,Running,Air Zoom,M,NaN,5550.99,NaN,0.00,23-11-2024,Retail,Mumbai,2453.57

#**BUSINESS UNDERSTANDING**

## **Study Case**

Nike adalah salah satu perusahaan sepatu terbesar di dunia dengan penjualan yang sangat tinggi di berbagai negara. Namun, meskipun penjualannya besar, perusahaan tetap menghadapi masalah seperti keuntungan yang tidak selalu stabil, adanya produk yang kurang menguntungkan, serta pemberian diskon yang belum tentu meningkatkan laba. Jika hal ini tidak dianalisis dengan baik, perusahaan bisa mengalami penurunan keuntungan meskipun penjualan terlihat ramai. Oleh karena itu, data penjualan perlu dianalisis untuk mengetahui produk, wilayah, dan cara penjualan mana yang paling menguntungkan agar Nike tetap konsisten dan terus mendapatkan keuntungan.

## **Business Objective**

Tujuan dari analisis ini adalah membantu Nike menjaga keuntungan tetap stabil meskipun persaingan tinggi dan strategi diskon sering digunakan. Perusahaan ingin mengetahui produk mana yang paling menguntungkan, wilayah mana yang memberikan kontribusi terbesar, serta saluran penjualan (Online atau Retail) mana yang lebih efektif. Selain itu, Nike ingin memastikan bahwa strategi diskon yang diberikan benar-benar meningkatkan penjualan tanpa mengurangi laba secara signifikan.

Dataset ini berisi data penjualan produk retail yang mencakup informasi seperti produk, wilayah, saluran penjualan (Online dan Retail), jumlah unit terjual, diskon, revenue, dan profit. Data ini digunakan untuk melihat kinerja penjualan serta menganalisis keuntungan perusahaan berdasarkan berbagai faktor yang memengaruhinya.

## **Assess Situation**

Saat ini, Nike memiliki banyak data penjualan yang mencatat produk yang terjual, wilayah penjualan, cara penjualan (Online atau Retail), jumlah barang yang terjual, diskon yang diberikan, serta keuntungan yang didapat. Namun dari data tersebut terlihat bahwa keuntungan tidak selalu stabil. Ada beberapa penjualan yang keuntungannya kecil bahkan ada yang rugi. Selain itu, belum diketahui dengan jelas apakah diskon yang diberikan benar-benar membantu meningkatkan keuntungan atau justru mengurangi laba. Jika kondisi ini dibiarkan saja, perusahaan bisa terus mengambil keputusan yang kurang tepat. Namun, karena data penjualan sudah tersedia, perusahaan bisa menganalisis dan memiliki peluang besar untuk memanfaatkannya agar strategi penjualan menjadi lebih efektif dan menguntungkan.

## **Analitic Goals & Project Plan**

Analitic Goals:
1. Mengetahui produk mana yang paling banyak menghasilkan keuntungan.
2. Melihat wilayah mana yang penjualannya paling tinggi dan paling rendah.
3. Membandingkan mana yang lebih menguntungkan, penjualan Online atau Retail.
4. Mengetahui apakah pemberian diskon benar-benar membantu meningkatkan keuntungan atau justru membuat rugi.
5. Mencari tahu penyebab adanya penjualan yang keuntungannya sangat kecil atau bahkan negatif.

Project Plan:
1. Melihat dan memahami isi dataset untuk mengetahui data apa saja yang tersedia.
2. Membersihkan data jika ada nilai kosong, salah input, atau data yang tidak sesuai.
3. Menghitung dan membandingkan total penjualan dan keuntungan berdasarkan produk, wilayah, dan cara penjualan.
4. Membuat grafik atau visualisasi agar hasil analisis lebih mudah dipahami.
5. Menarik kesimpulan dan memberikan saran agar Nike bisa meningkatkan keuntungan dan menjaga bisnis tetap stabil.